org: asharma
app: aws-node-cloudformation-api
service: aws-node-cloudformation-api
frameworkVersion: '3'
useDotenv: true

custom:
  serverless-offline: ## add this two lines
    httpPort: 4000 ## bellow "custom:" line

plugins:
  - serverless-offline
  - serverless-offline-dotenv

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /cloudformationStack/create
          method: post
      - http:
          path: /
          method: post
      - http:
          path: /hello
          method: get
    timeout: 30
    environment:
      ACCESSKEYID: ${env:ACCESSKEYID}
      SECRETACCESSKEY: ${env:SECRETACCESSKEY}
